version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./:/usr/local/docker/app
    command: 'npm run dev'
    tty: true
    restart: always
